name: Publish release

on:
  push:
    branches: [main]

jobs:
  release-please:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
